elif pathname == "/top-gainer":
         return (html.Div(children=[html.Div(className="container",
            children=[html.Hr(className="seperator"), html.Table(className="table table-hover",
            children=[html.Thead(children=[html.Tr(className="table-success", 
            children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")])]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")]),
            html.Tr(children=[html.Th(children="Ticker"), html.Td(children="Company Name"), 
            html.Td(children="Current Price"), html.Td(children="Percentage Change")])
            ])])]))     